name: google_auth

on:
  workflow_dispatch

env:
  PROJECT_ID: instaclause-dev-422515 # TODO: update Google Cloud project id

jobs:
  google-auth:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./infra
    permissions:
      contents: "read"
      id-token: "write"

    outputs:
      credentials_file_path: ${{ steps.google-auth.outputs.credentials }}
    steps:
      - uses: "actions/checkout@v4"

      - uses: "google-github-actions/auth@v2"
        id: google-auth
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set env
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ steps.google-auth.outputs.credentials }}" >> $GITHUB_ENV

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false