name: google_auth

on:
  workflow_dispatch: {}

jobs:
  google-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    outputs:
      credentials_file_path: ${{ steps.google-auth.outputs.credentials }}
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'google-github-actions/auth@v2'
        id: google-auth
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/990406339305/locations/global/workloadIdentityPools/github/providers/github'
      
  print-credentials:
    runs-on: ubuntu-latest
    needs: google-auth
    steps:
      - run: cat ${{ needs.google-auth.outputs.credentials_file_path }}